#!/usr/bin/env python3

# Dependencies:
# - python3.7 or later
# - gs (Ghostscript)

import argparse, os, re, subprocess, sys

def main(args):
    d=args.dimensions
    o=args.output
    if not o:
        o=f'empty-{d}.pdf'
    if os.path.exists(o):
        die(f'Output file {o} already exists')
    try:
        d = iso_size_to_mm(d)
    except:
        pass
    try:
        d = us_size_to_in(d)
    except:
        pass
    try:
        dm=m("^([0-9.]+)(pts|pt|in|cm|mm)x([0-9.]+)(pts|pt|in|cm|mm)$", d)
        wraw=float(dm[1])*({'pts':1,'pt':1,'in':72,'cm':72/2.54,'mm':72/25.4}[dm[2]])
        hraw=float(dm[3])*({'pts':1,'pt':1,'in':72,'cm':72/2.54,'mm':72/25.4}[dm[4]])
        w, h=round(wraw), round(hraw)
        def dim_desc_1(v, vraw, uval, unit):
            return f"{v}pt{'=' if v==vraw else '≈'}{uval}{'pt' if unit=='pts' else unit}"
        dim_desc = f"{dim_desc_1(w, wraw, dm[1], dm[2])} x {dim_desc_1(h, hraw, dm[3], dm[4])}"
    except:
        die('Invalid dimensions')
    pdf_proc = subprocess.run([
        'gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
        f'-sOutputFile={o}',
        '-sDEVICE=pdfwrite',
        f'-dDEVICEWIDTHPOINTS={w}', f'-dDEVICEHEIGHTPOINTS={h}',
    ], capture_output=True, text=True, check=True)
    assert pdf_proc.stdout == ""
    assert pdf_proc.stderr == ""
    print(f'Wrote {o} with dimensions {dim_desc}')

def m(pattern, string):
    match = re.match(pattern, string, re.DOTALL)
    if not match:
        return None
    if(match.group(0) != string):
        die(f'Pattern /${pattern}/ matched only part of string')
    ret = []
    for index in range((match.lastindex or 0)+1):
        ret.append(match.group(index))
    return ret

def iso_size_to_mm(d):
    dm=m("^([ABCabc])([0-9]|10)([Ll]?)$", d)
    short_dim=2**((int(dm[2])+{"A":1/2, "B":0, "C": 1/4}[dm[1].upper()])/-2)
    long_dim=short_dim*2**(1/2)
    wm, hm = (long_dim, short_dim) if dm[3] else (short_dim, long_dim)
    wmm, hmm = round(wm*1000), round(hm*1000)
    return f"{wmm}mmx{hmm}mm"

def us_size_to_in(d):
    return {"letter": "8.5inx11in", "letterl": "11inx8.5in",
            "legal": "8.5inx14in", "legall": "14inx8.5in",
            "ledger": "17inx11in", "ledgerl": "11inx17in",
            "tabloid": "11inx17in", "tabloidl": "17inx11in",
            }[d.lower()]

def die(reason):
    print(reason, file=sys.stderr)
    sys.exit(1)

pyver = sys.version_info
if not (pyver.major == 3 and pyver.minor >= 7):
    die("Requires python 3.7 or later")

# Override exit code 2 -> 1.
# This could have been achieved by ArgumentParser(..., exit_on_error=False), but
# that option doesn't exist in all supported python versions.
class OurArgumentParser(argparse.ArgumentParser):
    def exit(self, status=0, message=None):
        if status == 2: status = 1
        super().exit(status=status, message=message)

parser = OurArgumentParser(description='Create an empty, transparent PDF file.')
parser.add_argument('-o', '--output', metavar='FILE', type=str, help='Output PDF file. (default: empty-DIMENSIONS.pdf)')
parser.add_argument('-d', '--dimensions', type=str, default='3inx2in', help='The page dimensions of the file to create in WIDTHxHEIGHT format, e.g. 3inx2in. Supported units are pt, in, cm, and mm. Can also be an ISO or common US size e.g. A4, C5L or letter, with an L suffix meaning landscape. (default: 3inx2in)')

main(parser.parse_args(sys.argv[1:]))
