#!/usr/bin/env python3

# Dependencies:
# - python3.7 or later.
# - Python module `tkinter` (only needed for interactive use)
# - gs (Ghostscript)
# - qpdf or pdftk (pdf-sign will use pdftk if qpdf cannot be found)
# - pdfinfo.

################################################################################
# The MIT License (MIT)                                                        #
#                                                                              #
# Copyright © 2021-2025 Axel Svensson                                          #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of this software and associated documentation files (the “Software”), to     #
# deal in the Software without restriction, including without limitation the   #
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or  #
# sell copies of the Software, and to permit persons to whom the Software is   #
# furnished to do so, subject to the following conditions:                     #
#                                                                              #
# The above copyright notice and this permission notice shall be included in   #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE  #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER       #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING      #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS #
# IN THE SOFTWARE.                                                             #
################################################################################

import argparse, math, os, queue, re, shlex, shutil, subprocess, sys, tempfile, traceback, time

def die(reason):
    print(reason, file=sys.stderr)
    sys.exit(1)

pyver = sys.version_info
if not (pyver.major == 3 and pyver.minor >= 7):
    die("Requires python 3.7 or later")

CONTINUE_ON_WARNINGS = False

# Inspired by https://unix.stackexchange.com/a/141496
def main(args):
    global CONTINUE_ON_WARNINGS
    if args.continue_on_warnings:
        CONTINUE_ON_WARNINGS = True
    if not hasQpdf and not has("pdftk"):
        die("Needs either qpdf or pdftk installed")
    if not has("gs"):
        die("Needs Ghostscript installed")
    if not has("pdfinfo"):
        die("Needs pdfinfo installed")
    filePath=args.input
    if not isPdfFilename(filePath):
        die("Input file must end with .pdf (case insensitive)")
    if filePath.startswith('-'):
        # A cheap solution to a rare problem
        die("Input file may not start with a dash (-)")
    with tempfile.TemporaryDirectory() as tempdir:
        intmp=lambda fileName: os.path.join(tempdir, fileName)
        # Maybe flatten (make forms non-editable) before signing
        if args.flatten:
            inputPDF=intmp('input.pdf')
            qpdfOrPdftk([
                'qpdf',
                '--flatten-annotations=all',
                '--generate-appearances',
                filePath, inputPDF,
            ],[
                'pdftk', filePath,
                'output', inputPDF,
                'flatten'
            ])
        else:
            inputPDF=filePath
        steps = args.steps
        pageCount=pdfCountPages(inputPDF)
        def translatablePDF(path):
            cache = translatablePDF._cache
            if path not in cache:
                (w, h) = pdfGetSize(path)
                if not (1 < w and 1 < h):
                    die(f"The PDF at {path} is unusable as a signature due to too small dimensions.")
                (double_w, double_h) = (2*w, 2*h)
                testFile = intmp('translateTest.pdf')
                runc('gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
                     f'-sOutputFile={testFile}',
                     '-sDEVICE=pdfwrite',
                     f'-dDEVICEWIDTHPOINTS={double_w}',
                     f'-dDEVICEHEIGHTPOINTS={double_h}',
                     '-dFIXEDMEDIA',
                     '-c', f'<</BeginPage{{{w} {h} translate}}>> setpagedevice',
                     '-f', path)
                (test_w, test_h) = pdfGetSize(testFile)
                if abs(test_w - double_w) < 0.01 and abs(test_h - double_h) < 0.01:
                    # The pdf file at path can be translated correctly
                    cache[path] = path
                elif (test_w, test_h) == (w, h):
                    # The pdf file at path cannot be translated correctly.
                    # Rather, the size is unchanged. This can happen if the PDF
                    # has an explicit CropBox set, e.g. is created with
                    # gs -c '[/CropBox [0 0 100 50] /PAGES pdfmark'. We have to
                    # remove it to make the PDF translatable and usable as a
                    # signature.
                    translatableFileName = intmp(f'translatable{len(cache)}.pdf')
                    emptyFileName = intmp(f'empty{len(cache)}.pdf')
                    runc('gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
                         f'-sOutputFile={emptyFileName}',
                         '-sDEVICE=pdfwrite',
                         f'-dDEVICEWIDTHPOINTS={w}', f'-dDEVICEHEIGHTPOINTS={h}')
                    qpdfOrPdftk([
                        'qpdf', '--overlay', path, '--',
                        emptyFileName, translatableFileName,
                    ],[
                        'pdftk', emptyFileName,
                        'stamp', path,
                        'output', translatableFileName
                    ])
                    cache[path] = translatableFileName
                else:
                    die(f"The PDF at {path} is unusable as a signature. Reason unknown.")
            return cache[path]
        translatablePDF._cache={}
        displayMaxSize=Cell((400, 800))
        def textLabel(text): return f'"{text}"' if len(text) <= 20 else f'Custom text: "{text[:17]}"...'
        def initstep(i):
            s=steps[i]
            # The chosen page
            if s.page < -pageCount or s.page==0 or pageCount < s.page:
                die('Page number out of range')
            s.pageNumber=Cell(s.page if 0 < s.page else pageCount+s.page+1)
            @VolatileCell
            def pagePDF():
                for j in range(1, i+1):
                    prevStep = steps[i-j]
                    if prevStep.pageNumber() == s.pageNumber():
                        return prevStep.signedPagePDF()
                outFile=intmp(f'{i}-page.pdf')
                qpdfOrPdftk([
                    'qpdf', '--pages', '.', f'{s.pageNumber()}', '--',
                    inputPDF, outFile
                ],[
                    'pdftk', inputPDF,
                    'cat', str(s.pageNumber()),
                    'output', outFile])
                return outFile
            s.pageSize=Cell(lambda: pdfGetSize(pagePDF()))
            # The chosen signature
            if s.signature:
                if s.text:
                    die('--signature and --text cannot be specified together.')
                if not os.path.exists(s.signature):
                    die(f'File not found: {s.signature}')
                s.signatures=[('file', s.signature, s.signature)]
            elif s.batch:
                assert not s.signature
                if not s.text:
                    die('In batch mode, --signature or --text must be specified.')
                if len(s.text) > 1:
                    die('In batch mode, --text must be given only once.')
                validateText(s.text[0], True)
                s.signatures=[('text', textLabel(s.text[0]), s.text[0])]
            else:
                (signatureDir, signatureDirHelp)=getSignatureDirAndHelp()
                s.signatures=([('file', removePdfSuffix(x), os.path.join(signatureDir, x))
                             for x in filter(isPdfFilename, os.listdir(signatureDir))]
                            if signatureDir else [])
                s.signatures.sort()
                if not s.signatures and not s.text:
                    die(f'Could not find any usable signatures. No --signature, no --text, and ' +
                        ('no .pdf files found in {signatureDir}.'
                         if signatureDir else
                         f'no signature directory. The options considered for signature directory are: {signatureDirHelp}'))
                if s.text:
                    assert(len(s.text) > 0)
                    for text in s.text:
                        validateText(text, True)
                    s.signatures=[('text', textLabel(x), x) for x in s.text] + s.signatures
            s.signatureIndex=Cell(0)
            @Cell
            def signaturePath():
                (signType, _, content)=s.signatures[s.signatureIndex()]
                if signType=='cell':
                    (signType, _, content)=content()
                if signType=='file':
                    return content
                assert signType=='text'
                cache = signaturePath._cache
                if content in cache:
                    return cache[content]
                fileName=intmp(f"{i}-text{len(cache)}.pdf")
                text_to_pdf(content, fileName, 12, 1, True)
                cache[content]=fileName
                return fileName
            signaturePath._cache={}
            s.signatureSize=Cell(lambda: pdfGetSize(signaturePath()))
            s.signaturePositionX=Cell(lambda: parse_unit(s.x_coordinate, s.pageSize()[0], 'Invalid -x option', L=0, C=0.5, R=1)/s.pageSize()[0])
            s.signaturePositionY=Cell(lambda: parse_unit(s.y_coordinate, s.pageSize()[1], 'Invalid -y option', T=0, C=0.5, B=1)/s.pageSize()[1])
            anchorX = {'NW': 0, 'N': 0.5, 'NE': 1, 'W': 0, 'C': 0.5, 'E': 1, 'SW': 0, 'S': 0.5, 'SE': 1}[s.anchor]
            anchorY = {'NW': 1, 'N': 1, 'NE': 1, 'W': 0.5, 'C': 0.5, 'E': 0.5, 'SW': 0, 'S': 0, 'SE': 0}[s.anchor]
            s.signatureScale=Cell(0)
            @Cell
            def defaultResizeFactor():
                (pageWidth, pageHeight)=s.pageSize()
                maxSignatureWidth = parse_unit(s.width, pageWidth, 'Invalid -W option')
                maxSignatureHeight = parse_unit(s.height, pageHeight, 'Invalid -H option')
                (signatureWidth, signatureHeight)=s.signatureSize()
                if not (0 < s.resize_factor): die('Invalid -r option')
                return (s.resize_factor,
                        maxSignatureWidth / signatureWidth,
                        maxSignatureHeight / signatureHeight)
            s.defaultResizeFactor = defaultResizeFactor
            @VolatileCell
            def signaturePositionedPDF():
                (w, h)=s.pageSize()
                (sw, sh)=s.signatureSize()
                resize=1.1**s.signatureScale()*min(*s.defaultResizeFactor())
                dx=w*s.signaturePositionX()/resize - sw*anchorX
                dy=h*(1-s.signaturePositionY())/resize - sh*anchorY
                outFile=intmp(f'{i}-signature-positioned.pdf')
                runc('gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
                     f'-sOutputFile={outFile}',
                     '-sDEVICE=pdfwrite',
                     f'-dDEVICEWIDTHPOINTS={w}', f'-dDEVICEHEIGHTPOINTS={h}', '-dFIXEDMEDIA',
                     '-c', f'<</BeginPage{{{resize} {resize} scale {dx} {dy} translate}}>> setpagedevice',
                     '-f', translatablePDF(signaturePath()))
                return outFile
            # The signed page
            @VolatileCell
            def signedPagePDF():
                outFile=intmp(f'{i}-signed-page.pdf')
                qpdfOrPdftk([
                    'qpdf', '--overlay', signaturePositionedPDF(), '--',
                    pagePDF(), outFile,
                ],[
                    'pdftk', pagePDF(),
                    'stamp', signaturePositionedPDF(),
                    'output', outFile
                ])
                return outFile
            s.signedPagePDF = signedPagePDF
            # The signed page as PNG, for GUI use
            @Cell
            def displaySize():
                (maxWidth, maxHeight)=displayMaxSize()
                (pageWidth, pageHeight)=s.pageSize()
                scale=min(maxWidth/pageWidth, maxHeight/pageHeight)
                return (round(pageWidth*scale), round(pageHeight*scale))
            s.displaySize = displaySize
            @VolatileCell
            def displayPNG():
                (w, h)=s.displaySize()
                outFile=intmp(f'{i}-display.png')
                runc('gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
                     f'-sOutputFile={outFile}',
                     '-sDEVICE=pngalpha',
                     '-dMaxBitmap=2147483647',
                     f'-dDEVICEWIDTHPOINTS={w}', f'-dDEVICEHEIGHTPOINTS={h}', '-dFIXEDMEDIA', '-dPDFFitPage',
                     '-f', s.signedPagePDF())
                return outFile
            s.displayPNG = displayPNG
            # List of files and pages for output
            @Cell
            def outputList():
                prevList = [(inputPDF, 1, pageCount)] if i==0 else steps[i-1].outputList()
                accPages = 0
                for j, (pdfFile, startPage, endPage) in enumerate(prevList):
                    nofPages = endPage - startPage + 1
                    if accPages + nofPages < s.pageNumber():
                        accPages += nofPages
                        continue
                    ret = prevList[:j]
                    if accPages + 1 < s.pageNumber():
                        ret += [(pdfFile, startPage, startPage + s.pageNumber() - accPages - 2)]
                    ret += [(s.signedPagePDF(), 1, 1)]
                    if s.pageNumber() < accPages + nofPages:
                        ret += [(pdfFile, startPage + s.pageNumber() - accPages, endPage)]
                    ret += prevList[j+1:]
                    return ret
                assert False
            s.outputList = outputList
            # Context for GUI
            s.customText=Cell(('text', None, os.environ.get(
                "PDF_SIGN_UNDOCUMENTED_OVERRIDE_DEFAULT_CUSTOM_TEXT",
                time.strftime('%Y-%m-%d'))))
            s.customTextIndex = len(s.signatures)
            if not s.batch:
                s.is_last_interactive = all(step.batch for step in steps[i+1:])
        for i in range(len(steps)):
            initstep(i)

        # GUI
        doSign=True
        gui=not all(s.batch for s in steps)
        if gui:
            try:
                import tkinter as tk
                from tkinter import simpledialog
            except ModuleNotFoundError:
                die('Cannot find Python module `tkinter`, which is needed for interactive use.')
            doSign=False
            def first(items):
                return [*items][0]
            stepIndex = Cell(first(i for i in range(len(steps))
                                   if not steps[i].batch))
            @Cell
            def step(): return steps[stepIndex()]
            # Commands
            def uf(fun):
                def ret():
                    fun(step())
                    update()
                return ret
            @uf
            def cmd_prevPage(s):
                if 1<s.pageNumber():
                    s.pageNumber(s.pageNumber()-1)
            @uf
            def cmd_nextPage(s):
                if s.pageNumber()<pageCount:
                    s.pageNumber(s.pageNumber()+1)
            cmd_firstPage = uf(lambda s: s.pageNumber(1))
            cmd_lastPage = uf(lambda s: s.pageNumber(pageCount))
            cmd_nextSignature = uf(lambda s: s.signatureIndex((s.signatureIndex()+1)%len(s.signatures)))
            cmd_prevSignature = uf(lambda s: s.signatureIndex((s.signatureIndex()-1)%len(s.signatures)))
            cmd_moveSignatureUp = uf(lambda s: s.signaturePositionY(s.signaturePositionY()-0.02))
            cmd_moveSignatureDown = uf(lambda s: s.signaturePositionY(s.signaturePositionY()+0.02))
            cmd_moveSignatureLeft = uf(lambda s: s.signaturePositionX(s.signaturePositionX()-0.02))
            cmd_moveSignatureRight = uf(lambda s: s.signaturePositionX(s.signaturePositionX()+0.02))
            cmd_moveSignatureUpPt = uf(lambda s: s.signaturePositionY(s.signaturePositionY()-1/s.pageSize()[1]))
            cmd_moveSignatureDownPt = uf(lambda s: s.signaturePositionY(s.signaturePositionY()+1/s.pageSize()[1]))
            cmd_moveSignatureLeftPt = uf(lambda s: s.signaturePositionX(s.signaturePositionX()-1/s.pageSize()[0]))
            cmd_moveSignatureRightPt = uf(lambda s: s.signaturePositionX(s.signaturePositionX()+1/s.pageSize()[0]))
            cmd_enlargeSignature = uf(lambda s: s.signatureScale(s.signatureScale()+1))
            cmd_shrinkSignature = uf(lambda s: s.signatureScale(s.signatureScale()-1))
            def cmd_positionSignature(x, y):
                s=step()
                s.signaturePositionX(x)
                s.signaturePositionY(y)
                update()
            def cmd_selectSignatureByIndex(i):
                s=step()
                if i<len(s.signatures):
                    s.signatureIndex(i)
                    update()
            def cmd_customText():
                s=step()
                if s.signature:
                    return
                # Get text from user
                text = simpledialog.askstring(
                    "Custom Text",
                    "Input the text you want to stamp this PDF file with",
                    initialvalue=s.customText()[2])
                if text == None:
                    return
                # Validate text
                validateMsg = validateText(text, False)
                if validateMsg:
                    simpledialog.messagebox.showerror(
                        parent=root,
                        title="Invalid text",
                        message=validateMsg
                    )
                    return
                # Set text
                s.customText(('text', None, text))
                s.signatureIndex(s.customTextIndex)
                label='Custom text: ' + textLabel(text)
                s.placemenu.entryconfig(len(s.signatures) + 2, label=label)
                update()
            def cmd_abort():
                root.destroy()
            def cmd_sign():
                if not step().is_last_interactive:
                    return
                nonlocal doSign
                doSign=True
                root.destroy()
            def cmd_next():
                s=step()
                if s.is_last_interactive:
                    s.is_last_interactive = False
                    steps.append(args.new_sig_step())
                    initstep(len(steps)-1)
                oldIndex = stepIndex()
                stepIndex(first(i for i in range(len(steps))
                                if oldIndex < i and not steps[i].batch))
                update()
            # Error handling
            def tkerror(self, exc, val, tb):
                traceback.print_exception(exc, val, tb)
                sys.exit(1)
            tk.Tk.report_callback_exception = tkerror
            # Window and menu
            root = tk.Tk(className="pdf-sign")
            fix_scaling(root)
            rootmenu = tk.Menu(root)
            root.config(menu=rootmenu)
            filemenu = tk.Menu(rootmenu, tearoff=0)
            rootmenu.add_cascade(label="File", underline=0, menu=filemenu)
            filemenu.add_command(label='Sign & Exit', underline=0, accelerator='space / S', command=cmd_sign)
            filemenu.add_command(label='Sign & Next', underline=7, accelerator='N', command=cmd_next)
            filemenu.add_command(label='Abort & Exit', underline=0, accelerator='Esc / Q', command=cmd_abort)
            pagemenu = tk.Menu(rootmenu, tearoff=0)
            rootmenu.add_cascade(label="Page", underline=0, menu=pagemenu)
            pagemenu.add_command(label='First page', underline=0, accelerator='Home', command=cmd_firstPage)
            pagemenu.add_command(label='Previous page', underline=0, accelerator='PgUp', command=cmd_prevPage)
            pagemenu.add_command(label='Next page', underline=0, accelerator='PgDown', command=cmd_nextPage)
            pagemenu.add_command(label='Last page', underline=0, accelerator='End', command=cmd_lastPage)
            def updateMenu():
                s=step()
                assert not s.batch
                if not hasattr(s, 'placemenu'):
                    s.placemenu = tk.Menu(rootmenu, tearoff=0)
                    placemenu = s.placemenu
                    if not s.signature:
                        placemenu.add_command(label='Previous signature', underline=0, accelerator='Ctrl-Left', command=cmd_prevSignature)
                        placemenu.add_command(label='Next signature', underline=0, accelerator='Ctrl-Right', command=cmd_nextSignature)
                        placemenu.add_separator()
                        s.signatureControlVar=tk.IntVar()
                        s.signatureControlVar.set(s.signatureIndex())
                        def updateFromSignatureRadio():
                            if s.signatureControlVar.get() != s.signatureIndex():
                                s.signatureIndex(s.signatureControlVar.get())
                                update()
                        for index, (_, signatureText, _) in enumerate(s.signatures):
                            placemenu.add_radiobutton(
                                value=index,
                                label=f'{index+1}: {signatureText}',
                                underline=0 if index<9 else None,
                                variable=s.signatureControlVar,
                                accelerator=(str(index+1) if index<9 else None),
                                command=updateFromSignatureRadio)
                        s.signatures.append(('cell', None, s.customText))
                        placemenu.add_radiobutton(
                            value=s.customTextIndex,
                            label='Custom text: ' + textLabel(s.customText()[2]),
                            underline=7,
                            variable=s.signatureControlVar,
                            accelerator='T',
                            command=cmd_customText)
                        placemenu.add_separator()
                    placemenu.add_command(label='Enlarge signature', underline=0, accelerator='+', command=cmd_enlargeSignature)
                    placemenu.add_command(label='Shrink signature', underline=0, accelerator='-', command=cmd_shrinkSignature)
                    placemenu.add_separator()
                    placemenu.add_command(label='Move signature left 2%', underline=15, accelerator='Click / Left', command=cmd_moveSignatureLeft)
                    placemenu.add_command(label='Move signature down 2%', underline=15, accelerator='Click / Down', command=cmd_moveSignatureDown)
                    placemenu.add_command(label='Move signature up 2%', underline=15, accelerator='Click / Up', command=cmd_moveSignatureUp)
                    placemenu.add_command(label='Move signature right 2%', underline=15, accelerator='Click / Right', command=cmd_moveSignatureRight)
                    placemenu.add_separator()
                    placemenu.add_command(label='Move signature left 1pt', underline=17, accelerator='Click / Shift+Left', command=cmd_moveSignatureLeftPt)
                    placemenu.add_command(label='Move signature down 1pt', underline=16, accelerator='Click / Shift+Down', command=cmd_moveSignatureDownPt)
                    placemenu.add_command(label='Move signature up 1pt', underline=9, accelerator='Click / Shift+Up', command=cmd_moveSignatureUpPt)
                    placemenu.add_command(label='Move signature right 1pt', underline=16, accelerator='Click / Shift+Right', command=cmd_moveSignatureRightPt)
                rootmenu.delete(3) # This is ok whether or not it exists
                rootmenu.add_cascade(label="Signature", underline=1, menu=s.placemenu)
                filemenu.entryconfig(0, state="normal" if s.is_last_interactive else "disabled")
            # Extend TK Menu with keypad bindings
            root.bind_class("Menu", "<KP_Enter>", lambda event: root.tk.call(event.widget, "invoke", "active"))
            root.bind_class("Menu", "<KP_Up>", lambda event: root.tk.call("tk::MenuUpArrow", event.widget))
            root.bind_class("Menu", "<KP_Down>", lambda event: root.tk.call("tk::MenuDownArrow", event.widget))
            # Extend Entry widgets (used in simpledialog) to accept KP_Enter
            root.bind_class("Entry", "<KP_Enter>", lambda event: event.widget.event_generate('<Return>'))
            # Key bindings
            def bind(fun, *keys):
                for key in keys:
                    root.bind(key, lambda _: fun())
            bind(cmd_prevPage, '<Prior>', '<KP_Prior>', '<Page_Up>', '<KP_Page_Up>')
            bind(cmd_nextPage, '<Next>', '<KP_Next>', '<Page_Down>', '<KP_Page_Down>')
            bind(cmd_firstPage, '<Home>', '<KP_Home>')
            bind(cmd_lastPage, '<End>', '<KP_End>')
            bind(cmd_prevSignature, '<Control-Left>', '<Control-KP_Left>')
            bind(cmd_nextSignature, '<Control-Right>', '<Control-KP_Right>')
            bind(cmd_moveSignatureLeft, '<Left>', '<KP_Left>')
            bind(cmd_moveSignatureDown, '<Down>', '<KP_Down>')
            bind(cmd_moveSignatureUp, '<Up>', '<KP_Up>')
            bind(cmd_moveSignatureRight, '<Right>', '<KP_Right>')
            bind(cmd_moveSignatureLeftPt, '<Shift-Left>', '<Shift-KP_Left>')
            bind(cmd_moveSignatureDownPt, '<Shift-Down>', '<Shift-KP_Down>')
            bind(cmd_moveSignatureUpPt, '<Shift-Up>', '<Shift-KP_Up>')
            bind(cmd_moveSignatureRightPt, '<Shift-Right>', '<Shift-KP_Right>')
            bind(cmd_enlargeSignature, '<plus>', '<KP_Add>')
            bind(cmd_shrinkSignature, '<minus>', '<KP_Subtract>')
            bind(cmd_abort, '<Escape>', '<Q>', '<q>')
            bind(cmd_sign, '<space>', '<S>', '<s>')
            bind(cmd_next, '<N>', '<n>')
            bind(cmd_customText, '<T>', '<t>')
            bind(lambda: cmd_selectSignatureByIndex(0), '1')
            bind(lambda: cmd_selectSignatureByIndex(1), '2')
            bind(lambda: cmd_selectSignatureByIndex(2), '3')
            bind(lambda: cmd_selectSignatureByIndex(3), '4')
            bind(lambda: cmd_selectSignatureByIndex(4), '5')
            bind(lambda: cmd_selectSignatureByIndex(5), '6')
            bind(lambda: cmd_selectSignatureByIndex(6), '7')
            bind(lambda: cmd_selectSignatureByIndex(7), '8')
            bind(lambda: cmd_selectSignatureByIndex(8), '9')
            # Canvas and click binding
            root._docView=tk.Canvas(root, borderwidth=0, background='#ffffff')
            docViewMargin=5
            docViewMinDimension=50
            def onRootResize(event):
                rootWidth=root.winfo_width()
                rootHeight=root.winfo_height()
                newMaxDisplayDimensions=(max(rootWidth - 2 * docViewMargin, docViewMinDimension),
                                         max(rootHeight - 2 * docViewMargin, docViewMinDimension))
                if displayMaxSize() != newMaxDisplayDimensions:
                    displayMaxSize(newMaxDisplayDimensions)
                    update()
            root._docView.place(x=docViewMargin, y=docViewMargin)
            root._docViewIndex=root._docView.create_image(0, 0, anchor=tk.NW)
            root.bind('<Configure>', onRootResize)
            initWinSize=(root.winfo_screenwidth() * 0.8, root.winfo_screenheight() * 0.8)
            initWinSize=(min(initWinSize[0], initWinSize[1] * step().pageSize()[0] / step().pageSize()[1]),
                         min(initWinSize[1], initWinSize[0] * step().pageSize()[1] / step().pageSize()[0]))
            root.geometry(f"{int(initWinSize[0])}x{int(initWinSize[1])}")
            @Cell
            def updateTitle():
                s=step()
                root.title(f'Signing page {s.pageNumber()}/{pageCount} of {filePath}')
            # The update function triggers heavy PDF file operations, so we try
            # to avoid calling it too much. In particular,
            # 1) Depending on desktop environment and window manager, one or
            #    more resizes can happen soon after startup, triggering an
            #    update. We use the updateActive flag to avoid these, then
            #    instead update once 100 ms after startup.
            # 2) An interactive resizing process using the pointer can produce a
            #    lot of resizing events. We use the @tkthrottle decorator to
            #    reduce them.
            updateActive = False
            def soonAfterStart():
                nonlocal updateActive
                updateActive = True
                update()
            root.after(100, soonAfterStart)
            @tkthrottle(100, root)
            def update():
                if not updateActive:
                    return
                s = step()
                (w, h) = s.displaySize()
                root._docImg = tk.PhotoImage(file=s.displayPNG())
                root._docView.itemconfig(root._docViewIndex, image=root._docImg)
                root._docView.configure(width=w, height=h)
                updateTitle()
                updateMenu()
                if not s.signature:
                    if s.signatureControlVar.get() != s.signatureIndex():
                        s.signatureControlVar.set(s.signatureIndex())
            def onclick(event):
                x=event.x
                y=event.y
                canvasConfig=root._docView.config()
                canvasWidth=int(canvasConfig['width'][4])
                canvasHeight=int(canvasConfig['height'][4])
                cmd_positionSignature(x/canvasWidth, y/canvasHeight)
            root._docView.bind('<Button-1>', onclick)
            # Run GUI
            root.mainloop()
        # End of GUI
        if doSign:
            signedFilePath=args.output if args.output else f'{filePath[:-4]}.signed{filePath[-4:]}'
            if os.path.exists(signedFilePath):
                if args.existing=='backup':
                    backupFilePath=f'{signedFilePath}.backup{time.strftime("%Y%m%d_%H%M%S")}'
                    runc('mv',
                         signedFilePath,
                         backupFilePath)
                    print(f'Renamed {signedFilePath} to {backupFilePath}')
                elif args.existing=='fail':
                    die(f'Output file {signedFilePath} already exists')
                else:
                    assert args.existing=='overwrite'
            ol=steps[-1].outputList()
            def numToHandle(n):
                return ''.join([chr(ord(x)+0x11) for x in str(n)])
            qpdf_pages = []
            pdftk_handles = []
            pdftk_pages = []
            for idx, (path, fromPage, toPage) in enumerate(ol):
                qpdf_pages.append('.' if path==inputPDF else path)
                qpdf_pages.append(f'{fromPage}-{toPage}')
                pdftk_handle = f'P{numToHandle(idx)}'
                pdftk_handles.append(f'{pdftk_handle}={path}')
                pdftk_pages.append(f'{pdftk_handle}{fromPage}-{toPage}')
            qpdfOrPdftk([
                'qpdf',
                '--pages', *qpdf_pages,
                '--',
                inputPDF,
                signedFilePath,
            ],[
                'pdftk',
                *pdftk_handles,
                'cat',
                *pdftk_pages,
                'output', signedFilePath,
            ])
            print(f'Signed document saved as {signedFilePath}')
            if gui:
                print_how_to_automate_this_call(args, steps, pageCount)
        else:
            print('Aborted')

def parse_unit(text, one_hundred_percent, error_msg, **anchors):
    try:
        _, anchor, op, value, unit = m("^([A-Za-z]*)([\\+-]?)([0-9.]*)(pts?|in|cm|mm|%|)$", text)
        if op: assert anchor and value and unit
        elif anchor: assert not value and not unit
        else: assert value and unit
        return ({**anchors, '':0}[anchor.upper()]*one_hundred_percent +
                {'+': 1, '-': -1, '': 1}[op] *
                float(value or '0') *
                {'pts':1,'pt':1,'in':72,'cm':72/2.54,'mm':72/25.4,'%':one_hundred_percent/100,'':0}[unit])
    except:
        die(error_msg)

def runc(*cmd):
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.stdout:
        die(f"Command {' '.join(cmd)} produced output on stdout:\n"+
            proc.stdout.strip())
    if not CONTINUE_ON_WARNINGS and cmd[0] == "qpdf" and proc.returncode == 3:
        # https://qpdf.readthedocs.io/en/stable/cli.html#exit-status
        if proc.stderr:
            print(f"Command {' '.join(cmd)} produced output on stderr:\n"+
                  f"{proc.stderr.strip()}\n",
                  file=sys.stderr)
        die("qpdf exited with code 3, indicating warnings.\n"+
            "Run pdf-sign with flag -c or --continue-on-warnings to ignore.")
    if proc.stderr:
        print(f"Command {' '.join(cmd)} produced output on stderr:\n"+
              proc.stderr.strip(),
              file=sys.stderr)
        if not CONTINUE_ON_WARNINGS:
            die("\nRun pdf-sign with flag -c or --continue-on-warnings to ignore.")
    if proc.returncode != 0:
        die(f"Command {' '.join(cmd)} exited with code {proc.returncode}")

def has(cmd):
    return shutil.which(cmd) is not None
hasQpdf = has("qpdf")
def qpdfOrPdftk(qpdfCmd, pdftkCmd):
    assert qpdfCmd[0] == "qpdf" and pdftkCmd[0] == "pdftk"
    if hasQpdf:
        if CONTINUE_ON_WARNINGS:
            runc('qpdf', '--warning-exit-0', *qpdfCmd[1:])
        else:
            runc(*qpdfCmd)
    else:
        runc(*pdftkCmd)
    return True # Some lambdas above rely on this

def validateText(text, do_die):
    latin1_chars=set([*range(0x20, 0x7f), *range(0xa0, 0x100)])
    text_chars=set(map(ord, text))
    msg = ""
    if not text_chars.issubset(latin1_chars):
        msg = ("Error: Only non-control latin-1 characters are supported" +
               (" in --text" if do_die else "") +
               ". Unsupported characters: " + ', '.join(map(hex, text_chars - latin1_chars)))
    elif not (1 <= len(text) and len(text) <= 100):
        msg = "Text must be between 1 and 100 characters long."
    if not msg:
        return None
    if do_die:
        die(msg)
    return msg

def getSignatureDirAndHelp():
    def candidate(prevpath, prevhelptxt, nr, lbl, envvar, path):
        helptxt = f"{nr}) {lbl}"
        if prevhelptxt: helptxt = f"{prevhelptxt} {helptxt}"
        if envvar and not envvar in os.environ:
            helptxt += " which is not used since the environment variable is not set."
            return (prevpath, helptxt)
        path = os.path.expanduser(path)
        if not os.path.exists(path):
            helptxt += f" which is not used since {path} does not exist."
            return (prevpath, helptxt)
        if not os.path.isdir(path):
            helptxt += f" which is not used since {path} is not a directory."
            return (prevpath, helptxt)
        if prevpath:
            helptxt += f" which is valid, but not used since it's not the highest priority directory."
            return (prevpath, helptxt)
        helptxt += f" which resolves to {path} and IS USED as the signature directory."
        return (path, helptxt)
    (path, helptxt) = (None, None)
    (path, helptxt) = candidate(path, helptxt,
        1, '$PDF_SIGNATURE_DIR', 'PDF_SIGNATURE_DIR',
        os.environ.get('PDF_SIGNATURE_DIR'))
    (path, helptxt) = candidate(path, helptxt,
        2, '$XDG_CONFIG_HOME/pdf_signatures', 'XDG_CONFIG_HOME',
        os.path.join(os.environ.get('XDG_CONFIG_HOME') or '/', 'pdf_signatures'))
    (path, helptxt) = candidate(path, helptxt,
        3, '~/.config/pdf_signatures', None,
        '~/.config/pdf_signatures')
    (path, helptxt) = candidate(path, helptxt,
        4, '~/.pdf_signatures', None,
        '~/.pdf_signatures')
    return (path, helptxt)

# Simple dependency tracking.
# Init with a value or function to calculate the value.
# Update by calling with one argument (as in init).
# To retrieve an up-to-date value, call with no arguments.
# Calculations with unchanged inputs are skipped.
class Cell():
    currentCell=None
    def __init__(self, arg):
        self._arg=arg
        self._isuptodate=False
        self._needEval=True
        self._dependents=[]
        self._precedents=[]
        self._precedentvalues=[]
    def __call__(self, *args):
        if(len(args)==1):
            if self._arg != args[0]:
                self._arg=args[0]
                self._needEval=True
                self._dirty()
            return
        assert len(args)==0
        if not self._isuptodate:
            oldcell=Cell.currentCell
            Cell.currentCell=None
            for i in range(len(self._precedents)):
                p=self._precedents[i]
                oldval=self._precedentvalues[i]
                p()
                newval=p._cacheid()
                if oldval!=newval:
                    self._needEval=True
                    break
            if self._needEval:
                Cell.currentCell=self
                for p in self._precedents:
                    p._dependents.remove(self)
                self._precedents=[]
                self._precedentvalues=[]
                self._value=self._arg() if callable(self._arg) else self._arg
                self._needEval=False
            self._isuptodate=True
            Cell.currentCell=oldcell
        if(Cell.currentCell):
            self._dependents.append(Cell.currentCell)
            Cell.currentCell._precedents.append(self)
            Cell.currentCell._precedentvalues.append(self._cacheid())
        return self._value
    def _dirty(self):
        if self._isuptodate:
            self._isuptodate=False
            for d in self._dependents:
                d._dirty()
    def _cacheid(self):
        assert self._isuptodate
        return self._value
# When the return value is just a file name, the contents of that file needs to
# be taken into account in order to decide whether the "value" has changed. In
# these cases, we track the precedent values along the cell's own value.
class VolatileCell(Cell):
    def _cacheid(self):
        assert self._isuptodate
        return (self._value, self._precedentvalues)

# Keep this function in sync with pdf-from-text
def text_to_pdf(text, output, size, margin, center_baseline):
    # Use a standard PostScript / PDF font to avoid a dependency.
    FONT = "Times-Roman"
    # Validate text
    text_chars=set(map(ord, text))
    latin1_chars=set([*range(0x20, 0x7f), *range(0xa0, 0x100)])
    if not text_chars.issubset(latin1_chars):
        die(f"Error: Only non-control latin-1 characters are supported. Unsupported characters: {', '.join(map(hex, text_chars - latin1_chars))}")
    text.encode('latin-1').decode('latin-1') # Assertion. E.i., an exception here indicates a bug.
    with tempfile.TemporaryDirectory() as tempdir:
        # Write postscript file
        ps_file=os.path.join(tempdir, "file.ps")
        big=3*size # Arbitrary big-enough number
        text_len=len(text)
        w=text_len * big
        h=big * 3
        x=big
        y=big
        ps_text = (text
                   .replace("\\", "\\\\")
                   .replace("(", "\\(")
                   .replace(")", "\\)")
                   )
        def write_ps():
            with open(ps_file, "w", encoding="latin-1") as f:
                f.write('\n'.join([
                    "%!PS-Adobe-3.0",
                    f"%%BoundingBox: 0 0 {w} {h}",
                    "%%Pages: 1",
                    "%%EndComments",
                    "%%Page: 1 1",
                    f"/{FONT} findfont {size} scalefont setfont",
                    f"{x} {y} moveto",
                    f"({ps_text}) show",
                    "showpage"]))
        # Write postscript file with too big bounding box
        write_ps()
        # Get correct bounding box
        bbox_result = subprocess.run([
            "gs", '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
            # /prepress will among other things embed the font, which is
            # necessary to achieve consistent rendering across viewers.
            '-dPDFSETTINGS=/prepress',
            "-sDEVICE=bbox",
            ps_file
        ], capture_output=True, text=True, check=True)
        assert bbox_result.stdout == ""
        bbox = m(r'.*%%HiResBoundingBox: (\d+(\.\d+)?) (\d+(\.\d+)?) (\d+(\.\d+)?) (\d+(\.\d+)?)\n.*', bbox_result.stderr)
        if not bbox:
            die("Error: Unable to extract bounding box.")
        # Adjust bounding box
        llx, lly, urx, ury = float(bbox[1]), float(bbox[3]), float(bbox[5]), float(bbox[7])
        llx-=big; lly-=big; urx-=big; ury-=big # Undo initial text translation
        assert llx < urx and lly < ury # Sanity check
        w=math.ceil(2*margin + urx - llx) # Smallest int that can contain text and margins
        x=(w - urx + llx) / 2 - llx # Center text horizontally
        if center_baseline:
            h=math.ceil(2 * (margin + max(abs(lly), abs(ury)))) # Smallest int that can contain text and margin with centered baseline
            y=h/2 # Center baseline vertically
        else:
            h=math.ceil(2*margin + ury - lly) # Smallest int that can contain text and margins
            y=(h - ury + lly) / 2 - lly # Center text vertically
        # Write postscript file with correct bounding box
        write_ps()
        # Convert to PDF
        runc("gs", '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
            # /prepress will among other things embed the font, which is
            # necessary to achieve consistent rendering across viewers.
             '-dPDFSETTINGS=/prepress',
             "-o", output,
             "-sDEVICE=pdfwrite",
             f"-dDEVICEWIDTHPOINTS={w}",
             f"-dDEVICEHEIGHTPOINTS={h}",
             "-dFIXEDMEDIA",
             "-c", "[ /PAGES pdfmark",
             "-f", ps_file)

def tkthrottle(frequency, root):
    wait=1/frequency
    now=lambda: time.time()
    def decorator(fn):
        def throttled():
            if(throttled._suppressUntil<now()):
                fn()
            else:
                throttled._callAfterWait=True
            throttled._suppressUntil=now()+wait
            root.after(int(wait*1000+10), atend)
        def atend():
            if throttled._callAfterWait:
                if throttled._suppressUntil<now():
                    throttled._callAfterWait=False
                    fn()
        throttled._suppressUntil=0
        throttled._callAfterWait=False
        return throttled
    return decorator

def pdfCountPages(filePath):
    return int(fromCmdOutput(["pdfinfo", filePath], r"^.*\nPages: +([0-9]+)\n.*$")[1])

def pdfGetSize(filePath):
    [ignored, w, h, *ignored2]=fromCmdOutput(['pdfinfo', filePath], r'^.*\nPage size: +([0-9.]+) x ([0-9.]+) pts( \([A-Za-z0-9]+\))?\n.*$')
    return (float(w), float(h))

def m(pattern, string):
    match = re.match(pattern, string, re.DOTALL)
    if not match:
        return None
    if(match.group(0) != string):
        die(f'Pattern /${pattern}/ matched only part of string')
    ret = []
    for index in range((match.lastindex or 0)+1):
        ret.append(match.group(index))
    return ret

def isPdfFilename(filename):
    return m(r"^.*\.[Pp][Dd][Ff]$", filename)
def removePdfSuffix(filename):
    return m(r"^(.*)\.[Pp][Dd][Ff]$", filename)[1]

def fromCmdOutput(cmd, pattern):
    sp=subprocess.run(cmd, check=True, text=True, capture_output=True)
    if sp.stderr:
        print(f"Command {' '.join(cmd)} produced output on stderr:\n"+
              sp.stderr.strip(),
              file=sys.stderr)
        if not CONTINUE_ON_WARNINGS:
            die("\nRun pdf-sign with flag -c or --continue-on-warnings to ignore.")
    return m(pattern, sp.stdout)

# Copied from idlelib.run (Python standard library).
# Copied in order to avoid importing idlelib.run since that creates a ~/.idlerc directory.
def fix_scaling(root):
    """Scale fonts on HiDPI displays."""
    import tkinter.font
    scaling = float(root.tk.call('tk', 'scaling'))
    if scaling > 1.4:
        for name in tkinter.font.names(root):
            font = tkinter.font.Font(root=root, name=name, exists=True)
            size = int(font['size'])
            if size < 0:
                font['size'] = round(-0.75*size)

# Monkey-patch argparse if necessary
if not 'BooleanOptionalAction' in dir(argparse):
    class BooleanOptionalAction(argparse.Action):
        def __init__(self, option_strings, dest, default=None, type=None, choices=None, required=False, help=None, metavar=None):
            _option_strings = []
            for option_string in option_strings:
                _option_strings.append(option_string)
                if option_string.startswith('--'):
                    option_string = '--no-' + option_string[2:]
                    _option_strings.append(option_string)
            if help is not None and default is not None:
                help += f" (default: {default})"
            super().__init__(option_strings=_option_strings, dest=dest, nargs=0, default=default, type=type, choices=choices, required=required, help=help, metavar=metavar)
        def __call__(self, _parser, namespace, values, option_string=None):
            if option_string in self.option_strings:
                setattr(namespace, self.dest, not option_string.startswith('--no-'))
        def format_usage(self):
            return ' | '.join(self.option_strings)
    argparse.BooleanOptionalAction = BooleanOptionalAction

# Custom action for --next. Snapshot current .sig_* values into a new namespace,
# append it to .steps, and restore the values to parser-declared defaults.
class NextAction(argparse.Action):
    def __init__(self, option_strings, dest, **kwargs):
        super().__init__(option_strings, 'steps',
                         **{'nargs': 0, 'default': [], **kwargs})
    def __call__(self, this_parser, ns, values, option_string=None):
        sig = argparse.Namespace()
        for a in sig_actions(this_parser):
            setattr(sig, a.dest, getattr(ns, a.dest))
            setattr(ns, a.dest, a.default)
        ns.steps.append(sig)
def sig_actions(parser):
    return [a for a in parser._actions
            if a.option_strings and a.option_strings[0] in [
                    '-p', '-s', '-x', '-y', '-a', '-r', '-W', '-H', '-b', '-t']]

def getSignatureHelp():
    (path, helptxt) = getSignatureDirAndHelp()
    ret="""
        Path to file used as signature.
        Required in batch mode unless -t is given.
        In GUI mode, the user can choose among PDF files in the signature directory.
    """
    if path:
        ret += f"The signature directory is {path}, chosen from these options: {helptxt}"
    else:
        ret += f"Right now, no signature directory could be found. The options are: {helptxt}"
    return ret

# Override exit code 2 -> 1.
# This could have been achieved by ArgumentParser(..., exit_on_error=False), but
# that option doesn't exist in all supported python versions.
class OurArgumentParser(argparse.ArgumentParser):
    def exit(self, status=0, message=None):
        if status == 2: status = 1
        super().exit(status=status, message=message)

parser = OurArgumentParser(description='Sign a PDF file, with a non-cryptographic squiggle.',
                           epilog='pdf-sign v0.1.0 © 2021-2025 Axel Svensson')
parser.add_argument('input', metavar='input.pdf', type=str, help='Input PDF file.')
parser.add_argument('-p', '--page', type=int, default=-1, help='The page to sign, negative for counting from the end. (default: -1)')
parser.add_argument('-s', '--signature', type=str, help=getSignatureHelp())
parser.add_argument('-x', '--x-coordinate', type=str, default="C", help='Horizontal coordinate of signature e.g. 25%%, R-3cm or C. Letters L, C and R means left edge, center and right edge respectively. The letter can be followed by + or -, a number and a unit. Supported units are pt, in, cm, mm and %% (percent of page width). Prefix L+ can be left out. (default: C)')
parser.add_argument('-y', '--y-coordinate', type=str, default="B-25%", help='Vertical coordinate of signature e.g. C+25%% or B-2in. Letters T, C and B means top edge, center and bottom edge respectively. The letter can be followed by + or -, a number and a unit. Supported units are pt, in, cm, mm and %% (percent of page height). Prefix T+ can be left out. (default: B-25%%)')
parser.add_argument('-a', '--anchor', type=str.upper, choices=['NW', 'N', 'NE', 'W', 'C', 'E', 'SW', 'S', 'SE'], default="C", help='Anchor point in signature. The signature will be translated to position the anchor point at the location defined by -x and -y. (default: C)')
parser.add_argument('-r', '--resize-factor', type=float, default=1.0, help='Resize signature by this factor. If this would make the signature larger than allowed by -W or -H, then instead use the maximum allowed size.')
parser.add_argument('-W', '--width', type=str, default="50%", help='Maximum width of signature, a number followed by a unit. Supported units are pt, in, cm, mm and %% (percent of page width). (default: 50%%)')
parser.add_argument('-H', '--height', type=str, default="50%", help='Maximum height of signature, a number followed by a unit. Supported units are pt, in, cm, mm and %% (percent of page height). (default: 50%%)')
parser.add_argument('-o', '--output', type=str, help='Output file. (default: Add ".signed" before the extension)')
parser.add_argument('-b', '--batch', action=argparse.BooleanOptionalAction, default=False, help='Batch mode: do not show GUI. (default: False)')
parser.add_argument('-f', '--flatten', action=argparse.BooleanOptionalAction, default=True, help='Flatten before signing, preventing subsequent changes in PDF forms. (default: True)')
parser.add_argument('-e', '--existing', type=str.lower, choices=['backup', 'overwrite', 'fail'], default='backup', help='What to do if output file exists. (default: backup)')
parser.add_argument('-t', '--text', type=str, action='append', help='In GUI mode, a text option to be added to the list of signatures (can be repeated). In batch mode only one can be given, and will be used instead of --signature.')
parser.add_argument('-c', '--continue-on-warnings', action=argparse.BooleanOptionalAction, default=False, help='Do not fail on warnings from sub processes. (default: False)')
parser.add_argument('-n', '--next', action=NextAction, help='To add multiple signatures, use --next between each set of signature options. This includes all options except -chofe. For example, you can add the date in batch mode and thereafter use the GUI to sign, by running: pdf-sign -bt $(date -I) -ny 80%% input.pdf')

parsed_args = parser.parse_args((sys.argv[1:] or ['-h']) + ['-n'])
for a in sig_actions(parser):
    delattr(parsed_args, a.dest)

def new_sig_step():
    sig = argparse.Namespace()
    for a in sig_actions(parser):
        setattr(sig, a.dest, a.default)
    return sig
parsed_args.new_sig_step = new_sig_step

def print_how_to_automate_this_call(args, steps, pageCount):
    txt=["pdf-sign"]
    JOIN, SP, NBSP = object(), object(), object()
    state = SP
    def add(*things):
        nonlocal txt, state
        for thing in things:
            if thing in [JOIN, SP, NBSP]:
                state = thing
                continue
            is_short = len(thing)==2 and thing.startswith('-')
            if state == JOIN:
                txt[-1] += thing[1:] if is_short else thing
            elif state == SP:
                txt.append(thing)
            else:
                txt[-1]+=f' {thing}'
            state = JOIN if is_short else SP
    # -f
    if not args.flatten: add('--no-flatten')
    # -e
    if args.existing != 'backup': add('-e', args.existing)
    # -c
    if args.continue_on_warnings: add('-c')
    # steps
    def f(fl):
        i=0
        while not math.isclose(fl, round(fl, i)):
            i+=1
        ret = str(round(fl, i))
        if ret.endswith(".0"): return ret[:-2]
        return ret
    def p(path):
        home = os.path.expanduser("~/")
        if path.startswith(home):
            return f'~/{shlex.quote(path[len(home):])}'
        else:
            return shlex.quote(path)
    for i, s in enumerate(steps):
        if i: add('-n')
        add('-b')
        if s.batch:
            if s.page != -1: add('-p', str(s.page))
            if s.signature: add('-s', NBSP, p(s.signature))
            if s.text: add('-t', shlex.quote(s.text[0]), SP)
            if s.x_coordinate != 'C': add('-x', s.x_coordinate)
            if s.y_coordinate != 'B-25%': add('-y', s.y_coordinate)
            if s.anchor != 'C': add('-a', s.anchor)
            if s.resize_factor != 1.0: add('-r', f(s.resize_factor))
            if s.width != '50%': add('-W', s.width)
            if s.height != '50%': add('-H', s.height)
        else:
            # -p
            if s.pageNumber() != pageCount:
                add('-p', str(s.pageNumber()))
            # -st
            (signType, _, content)=s.signatures[s.signatureIndex()]
            if signType=='cell':
                (signType, _, content)=content()
            if signType == 'file':
                add('-s', NBSP, p(content))
            else:
                add('-t', shlex.quote(content), SP)
            # -xy
            if s.signaturePositionX() != 0.5:
                add('-x', f'{f(s.signaturePositionX()*100)}%')
            if s.signaturePositionY() != 0.75:
                add('-y', f'{f(s.signaturePositionY()*100)}%')
            # -a
            if s.anchor != 'C': add('-a', s.anchor)
            # -rWH
            resize_r, resize_w, resize_h = s.defaultResizeFactor()
            resize = min(resize_r, resize_w, resize_h)
            scale = 1.1**s.signatureScale()
            (signature_width, signature_height)=s.signatureSize()
            (page_width, page_height)=s.pageSize()
            resize_tot = resize * scale
            w = signature_width/page_width*resize_tot
            h = signature_height/page_height*resize_tot
            c=math.ceil
            if resize == resize_r:
                if resize_tot != 1:
                    add('-r', f(resize_tot))
                if w > 0.5:
                    add('-W', f'{f(c(w)*100)}%')
                if h > 0.5:
                    add('-H', f'{f(c(h)*100)}%')
            else:
                if resize_tot > 1:
                    add('-r', f(c(resize_tot)))
                arg, opt, resize_d, other_opt, other_factor = (
                    (s.width, '-W', resize_w, '-H', h)
                    if resize == resize_w else
                    (s.height, '-H', resize_h, '-W', w))
                if scale == 1:
                    if arg != '50%':
                        add(opt, arg)
                else:
                    add(opt, f'{f(resize_d*scale*100)}%')
                if other_factor > 0.5:
                    add(other_opt, f'{f(c(other_factor)*100)}%')
    # -o
    if args.output: add('-o', NBSP, p(args.output))
    # input
    add(SP, p(args.input))
    # print
    pre = "How to automate this:"
    cols = shutil.get_terminal_size().columns
    oneline = ' '.join([pre, *txt])
    if len(oneline) < cols:
        print(oneline)
    else:
        print(pre)
        print('  ', end='')
        rem = cols - 4
        while txt:
            [thing, *txt] = txt
            print(thing, end='')
            rem -= len(thing)
            if txt and rem < len(txt[0]) + 4:
                print(' \\\n    ', end='')
                rem = cols - 6
            elif txt:
                print(' ', end='')
        print('')

main(parsed_args)
