#!/usr/bin/env python3

#Dependencies:
# - python3.7 or later
# - gs (Ghostscript)

import argparse, math, os, re, subprocess, sys, tempfile

def main():
    parser = OurArgumentParser(description="Create a correctly cropped PDF from one line of text. Only Latin-1 character set is supported.")
    parser.add_argument("-t", "--text", required=True, help="Text to be converted to PDF.")
    parser.add_argument("-o", "--output", required=True, help="Output PDF file.")
    parser.add_argument("-s", "--size", type=int, default=12, help="Font size in points (default 12).")
    parser.add_argument("-m", "--margin", type=int, default=1, help="Margin in points (default 1).")
    parser.add_argument('-b', '--baseline', action=argparse.BooleanOptionalAction, default=False, help='Center baseline vertically (default: False).')
    args = parser.parse_args()
    text_to_pdf(args.text, args.output, args.size, args.margin, args.baseline)

CONTINUE_ON_WARNINGS = False

# Monkey-patch argparse if necessary
if not 'BooleanOptionalAction' in dir(argparse):
    class BooleanOptionalAction(argparse.Action):
        def __init__(self, option_strings, dest, default=None, type=None, choices=None, required=False, help=None, metavar=None):
            _option_strings = []
            for option_string in option_strings:
                _option_strings.append(option_string)
                if option_string.startswith('--'):
                    option_string = '--no-' + option_string[2:]
                    _option_strings.append(option_string)
            if help is not None and default is not None:
                help += f" (default: {default})"
            super().__init__(option_strings=_option_strings, dest=dest, nargs=0, default=default, type=type, choices=choices, required=required, help=help, metavar=metavar)
        def __call__(self, _parser, namespace, values, option_string=None):
            if option_string in self.option_strings:
                setattr(namespace, self.dest, not option_string.startswith('--no-'))
        def format_usage(self):
            return ' | '.join(self.option_strings)
    argparse.BooleanOptionalAction = BooleanOptionalAction

# Keep this function in sync with pdf-sign
def text_to_pdf(text, output, size, margin, center_baseline):
    # Use a standard PostScript / PDF font to avoid a dependency.
    FONT = "Times-Roman"
    # Validate text
    text_chars=set(map(ord, text))
    latin1_chars=set([*range(0x20, 0x7f), *range(0xa0, 0x100)])
    if not text_chars.issubset(latin1_chars):
        die(f"Error: Only non-control latin-1 characters are supported. Unsupported characters: {', '.join(map(hex, text_chars - latin1_chars))}")
    text.encode('latin-1').decode('latin-1') # Assertion. E.i., an exception here indicates a bug.
    with tempfile.TemporaryDirectory() as tempdir:
        # Write postscript file
        ps_file=os.path.join(tempdir, "file.ps")
        big=3*size # Arbitrary big-enough number
        text_len=len(text)
        w=text_len * big
        h=big * 3
        x=big
        y=big
        ps_text = (text
                   .replace("\\", "\\\\")
                   .replace("(", "\\(")
                   .replace(")", "\\)")
                   )
        def write_ps():
            with open(ps_file, "w", encoding="latin-1") as f:
                f.write('\n'.join([
                    "%!PS-Adobe-3.0",
                    f"%%BoundingBox: 0 0 {w} {h}",
                    "%%Pages: 1",
                    "%%EndComments",
                    "%%Page: 1 1",
                    f"/{FONT} findfont {size} scalefont setfont",
                    f"{x} {y} moveto",
                    f"({ps_text}) show",
                    "showpage"]))
        # Write postscript file with too big bounding box
        write_ps()
        # Get correct bounding box
        bbox_result = subprocess.run([
            "gs", '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
            # /prepress will among other things embed the font, which is
            # necessary to achieve consistent rendering across viewers.
            '-dPDFSETTINGS=/prepress',
            "-sDEVICE=bbox",
            ps_file
        ], capture_output=True, text=True, check=True)
        assert bbox_result.stdout == ""
        bbox = m(r'.*%%HiResBoundingBox: (\d+(\.\d+)?) (\d+(\.\d+)?) (\d+(\.\d+)?) (\d+(\.\d+)?)\n.*', bbox_result.stderr)
        if not bbox:
            die("Error: Unable to extract bounding box.")
        # Adjust bounding box
        llx, lly, urx, ury = float(bbox[1]), float(bbox[3]), float(bbox[5]), float(bbox[7])
        llx-=big; lly-=big; urx-=big; ury-=big # Undo initial text translation
        assert llx < urx and lly < ury # Sanity check
        w=math.ceil(2*margin + urx - llx) # Smallest int that can contain text and margins
        x=(w - urx + llx) / 2 - llx # Center text horizontally
        if center_baseline:
            h=math.ceil(2 * (margin + max(abs(lly), abs(ury)))) # Smallest int that can contain text and margin with centered baseline
            y=h/2 # Center baseline vertically
        else:
            h=math.ceil(2*margin + ury - lly) # Smallest int that can contain text and margins
            y=(h - ury + lly) / 2 - lly # Center text vertically
        # Write postscript file with correct bounding box
        write_ps()
        # Convert to PDF
        runc("gs", '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dQUIET',
            # /prepress will among other things embed the font, which is
            # necessary to achieve consistent rendering across viewers.
             '-dPDFSETTINGS=/prepress',
             "-o", output,
             "-sDEVICE=pdfwrite",
             f"-dDEVICEWIDTHPOINTS={w}",
             f"-dDEVICEHEIGHTPOINTS={h}",
             "-dFIXEDMEDIA",
             "-c", "[ /PAGES pdfmark",
             "-f", ps_file)

def runc(*cmd):
    proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    assert proc.stdout == ""
    assert proc.stderr == ""

def m(pattern, string):
    match = re.match(pattern, string, re.DOTALL)
    if not match:
        return None
    if(match.group(0) != string):
        die(f'Pattern /${pattern}/ matched only part of string')
    ret = []
    for index in range((match.lastindex or 0)+1):
        ret.append(match.group(index))
    return ret

def die(reason):
    print(reason, file=sys.stderr)
    sys.exit(1)

pyver = sys.version_info
if not (pyver.major == 3 and pyver.minor >= 7):
    die("Requires python 3.7 or later")

# Override exit code 2 -> 1.
# This could have been achieved by ArgumentParser(..., exit_on_error=False), but
# that option doesn't exist in all supported python versions.
class OurArgumentParser(argparse.ArgumentParser):
    def exit(self, status=0, message=None):
        if status == 2: status = 1
        super().exit(status=status, message=message)

if __name__ == "__main__":
    main()
